[project]
name = "cra_risk_management"
version = "0.1.2"
description = "Package to geospatial analysis and statistics."
authors = [
    {name = "Sebástian Andrés Narváez Salcedo", email = "snarvaezwrm@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas (>=3.0.0)",
    "statsmodels (>=0.14.0)",
    "matplotlib (>=3.11.0)",
    "prepare-wfs-data (>=0.1.2)"
]

[tool.poetry]
packages = [{include = "cra_risk_management", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "jupyterlab (>=4.6.2)"
]

[tool.ruff]
target-version = "py312"
line-length = 88

[tool.ruff.lint]
preview = true
select = ["ALL"]
ignore = [
    "missing-copyright-notice",
    "incorrect-blank-line-before-class",          # incompatible with D211
    "multi-line-summary-second-line",             # incompatible with D212
    "missing-trailing-comma",                     # incompatible with formatter
    "single-line-implicit-string-concatenation",  # incompatible with formatter
]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["undocumented-public-module", "undocumented-public-package"]
